language: cpp

compiler:
  - gcc

before_install:
  - echo $LANG
  - echo $LC_ALL
  - sudo apt-get install python-software-properties
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install gcc-4.8
  - sudo apt-get install g++-4.8
  - sudo apt-get install binutils-gold
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50

before_script:
  - mkdir src inst obj
  - svn checkout -r209839 http://llvm.org/svn/llvm-project/llvm/trunk src > /dev/null
  - svn checkout -r209839 http://llvm.org/svn/llvm-project/cfe/trunk src/tools/clang > /dev/null
  - git clone https://github.com/vgvassilev/clad.git src/tools/clad
  - cd src
  - cat patches tools/clad/patches/*.diff | patch -p0
  - cd ../obj
  - travis_retry ../src/configure --prefix=`pwd`/../inst --disable-docs --disable-bindings --disable-visibility-inlines-hidden --disable-clang-rewriter --disable-clang-static-analyzer --disable-clang-arcmt --disable-compiler-version-checks --enable-targets=host

script:
  - travis_retry make -j4 -k
  - cd tools/clad
  - make test LIT_ARGS=--no-progress-bar

branches:
  only:
    - master

notifications:
  recipients:
    - vvasilev@cern.ch
    - mrtn.vassilev@gmail.com
    - alexander_penev@yahoo.com

  email:
    on_success: change
    on_failure: always
  #irc:
  #channels:
    #- "chat.freenode.net#rubinius"
  template:
    - "%{repository}/%{branch} (%{commit} - %{author}): %{message}"

os:
  - linux
  - osx
